/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'appliedAt' : IDL.Int,
  'applicantId' : IDL.Principal,
  'name' : IDL.Text,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
  'email' : IDL.Text,
  'resumeSummary' : IDL.Text,
  'relevantExperience' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'company' : IDL.Text,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateJob' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'appliedAt' : IDL.Int,
    'applicantId' : IDL.Principal,
    'name' : IDL.Text,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
    'email' : IDL.Text,
    'resumeSummary' : IDL.Text,
    'relevantExperience' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'company' : IDL.Text,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateJob' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };