/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : string,
  'appliedAt' : bigint,
  'applicantId' : Principal,
  'name' : string,
  'jobId' : bigint,
  'coverLetter' : string,
  'email' : string,
  'resumeSummary' : string,
  'relevantExperience' : string,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'isOpen' : boolean,
  'company' : string,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJob' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    undefined
  >,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllApplications' : ActorMethod<[], Array<Application>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[bigint], Job>,
  'getJobs' : ActorMethod<[], Array<Job>>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateApplicationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateJob' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];